//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buddhika.GetMyPublicIp.ActivityLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class GetMyPublicIp : global::System.Configuration.ApplicationSettingsBase {
        
        private static GetMyPublicIp defaultInstance = ((GetMyPublicIp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GetMyPublicIp())));
        
        public static GetMyPublicIp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("getmypublicipservice@gmail.com")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetMyPublicIpService6563")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("It\'s Your Public Ip at {0}")]
        public string Subject {
            get {
                return ((string)(this["Subject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" <h1> Wanna know your public Ip</h1> <p> <b> {0} </b> is your new public Ip</p> <" +
            "p>no need to thank and it\'s my pleasure to keep you update </p> ")]
        public string SuccessBodyHtml {
            get {
                return ((string)(this["SuccessBodyHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bnwimalasena@gmail.com")]
        public string ToAddress {
            get {
                return ((string)(this["ToAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<h1> ohhhh , can\'t tell your public IP </h1> <br/> <p> IP Details providing Web S" +
            "ervice seems not working.</p> ")]
        public string FailBodyHtml {
            get {
                return ((string)(this["FailBodyHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sorry, Can\'t fetch your public ip at {0}")]
        public string FailSubject {
            get {
                return ((string)(this["FailSubject"]));
            }
        }
    }
}
